apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T10:48:45Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "4978"
  uid: c5466807-94ad-41a6-9600-ef18a8fcd056
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.111.80.104
  clusterIPs:
  - 10.111.80.104
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30208
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
